@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddDoctorParser" as AddDoctorParser LOGIC_COLOR
participant "d:AddDoctorCommand" as AddDoctorCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":ClinicAssistant" as ClinicAssistant MODEL_COLOR
participant ":UniqueDoctorList" as UniqueDoctorList MODEL_COLOR
participant ":ObservableList" as ObservableList MODEL_COLOR
end box

[-> LogicManager : execute("add_Doctor /n Kevin")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add_Doctor /n Kevin")
activate AddressBookParser

create AddDoctorParser
AddressBookParser -> AddDoctorParser
activate AddDoctorParser

AddDoctorParser --> AddressBookParser
deactivate AddDoctorParser

AddressBookParser ->  AddDoctorParser : parse("Kevin")
activate  AddDoctorParser

create AddDoctorCommand
AddDoctorParser ->  AddDoctorCommand
activate  AddDoctorCommand

AddDoctorCommand --> AddDoctorParser : d
deactivate   AddDoctorCommand

 AddDoctorParser --> AddressBookParser : d
deactivate  AddDoctorParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
 AddDoctorParser -[hidden]-> AddressBookParser
destroy AddDoctorParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager ->  AddDoctorCommand : execute()
activate  AddDoctorCommand

AddDoctorCommand -> ModelManager : addDoctor("Kevin")
activate ModelManager

ModelManager -> ClinicAssistant : addDoctor("Kevin")
activate ClinicAssistant

ClinicAssistant -> UniqueDoctorList : addDoctor("Kevin")
activate UniqueDoctorList

UniqueDoctorList -> ObservableList : add()
activate ObservableList

ObservableList --> UniqueDoctorList
deactivate ObservableList

UniqueDoctorList --> ClinicAssistant :
deactivate UniqueDoctorList

ClinicAssistant --> ModelManager
deactivate ClinicAssistant

ModelManager -->  AddDoctorCommand
deactivate ModelManager


create CommandResult
AddDoctorCommand -> CommandResult
activate CommandResult

CommandResult -->  AddDoctorCommand
deactivate CommandResult

AddDoctorCommand --> LogicManager : result
deactivate AddDoctorCommand

[<--LogicManager
deactivate LogicManager
@enduml
