@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClinicAssistantParser" as ClinicAssistantParser LOGIC_COLOR
participant ":FindByNricCommandParser" as FindByNricCommandParser LOGIC_COLOR
participant ":FindByNricCommand" as FindByNricCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant "predicate:NricContainsKeywordPredicate" as NricContainsKeywordPredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":FilteredList" as FilteredList MODEL_COLOR
end box

[-> LogicManager : execute("find_nric T0123456E")
activate LogicManager

LogicManager -> ClinicAssistantParser : parseCommand("find_nric T0123456E")
activate ClinicAssistantParser

create FindByNricCommandParser
ClinicAssistantParser -> FindByNricCommandParser
activate FindByNricCommandParser

FindByNricCommandParser --> ClinicAssistantParser
deactivate FindByNricCommandParser

ClinicAssistantParser -> FindByNricCommandParser : parse("T0123456E")
activate FindByNricCommandParser

create FindByNricCommand
FindByNricCommandParser -> FindByNricCommand
activate FindByNricCommand

FindByNricCommand --> FindByNricCommandParser
deactivate FindByNricCommand

FindByNricCommandParser --> ClinicAssistantParser
deactivate FindByNricCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindByNricCommandParser -[hidden]-> ClinicAssistantParser
destroy FindByNricCommandParser

ClinicAssistantParser --> LogicManager
deactivate ClinicAssistantParser

LogicManager -> FindByNricCommand : execute()
activate FindByNricCommand

create NricContainsKeywordPredicate
FindByNricCommand -> NricContainsKeywordPredicate
activate NricContainsKeywordPredicate

NricContainsKeywordPredicate --> FindByNricCommand : predicate
deactivate NricContainsKeywordPredicate

FindByNricCommand -> Model : updateFilterPersonList(predicate)
activate Model

Model -> FilteredList : setPredicate(predicate)
activate FilteredList

FilteredList --> Model
deactivate FilteredList

Model --> FindByNricCommand
deactivate Model

create CommandResult
FindByNricCommand -> CommandResult
activate CommandResult

CommandResult --> FindByNricCommand : result
deactivate CommandResult

FindByNricCommand --> LogicManager : result
deactivate FindByNricCommand

[<--LogicManager
deactivate LogicManager
@enduml
