@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClinicAssistantParser" as ClinicAssistantParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant ":FindCommand" as FindCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant "predicate:NameContainsKeywordPredicate" as NameContainsKeywordPredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":FilteredList" as FilteredList MODEL_COLOR
end box

[-> LogicManager : execute("find Alex")
activate LogicManager

LogicManager -> ClinicAssistantParser : parseCommand("find Alex")")
activate ClinicAssistantParser

create FindCommandParser
ClinicAssistantParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> ClinicAssistantParser
deactivate FindCommandParser

ClinicAssistantParser -> FindCommandParser : parse("Alex")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser
deactivate FindCommand

FindCommandParser --> ClinicAssistantParser
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> ClinicAssistantParser
destroy FindCommandParser

ClinicAssistantParser --> LogicManager
deactivate ClinicAssistantParser

LogicManager -> FindCommand : execute()
activate FindCommand

create NameContainsKeywordPredicate
FindCommand -> NameContainsKeywordPredicate
activate NameContainsKeywordPredicate

NameContainsKeywordPredicate --> FindCommand : predicate
deactivate NameContainsKeywordPredicate

FindCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model -> FilteredList : setPredicate(predicate)
activate FilteredList

FilteredList --> Model
deactivate FilteredList

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand : result
deactivate CommandResult

FindCommand --> LogicManager : result
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
